"""ExamZen Flask Backend Server.

Provides API routes for journaling, sentiment/stress analysis via Gemini,
burnout trajectory prediction, stress DNA reports, quick coping tools,
emotional trend dashboard calculation, and chat functionality.
"""

import datetime
import json
import os
import re
import uuid
from flask import Flask, jsonify, request, send_from_directory
from flask_cors import CORS
from dotenv import load_dotenv
import google.generativeai as genai

# Load environment variables
load_dotenv()

app = Flask(__name__, static_folder="static")

# Configure CORS
ENV = os.environ.get("FLASK_ENV", "development")
if ENV == "development":
    CORS(app, resources={r"/*": {"origins": ["http://localhost:5000", "http://127.0.0.1:5000", "http://localhost:8000"]}})
else:
    CORS(app)

# Constants
DATA_FILE = "journal_data.json"
MAX_JOURNAL_CHARS = 2000
MIN_BURNOUT_ENTRIES = 3
GEMINI_MODEL_NAME = "gemini-2.5-flash"

# Configure Gemini
api_key = os.environ.get("GEMINI_API_KEY")
if api_key:
    genai.configure(api_key=api_key)


@app.before_request
def check_api_key():
    """Enforces that the GEMINI_API_KEY environment variable is set for all API endpoints."""
    # Skip check for frontend static files and root route
    exempt_paths = ["/", "/index.html", "/static/style.css", "/static/script.js", "/favicon.ico"]
    if request.path in exempt_paths or request.path.startswith("/static/"):
        return None

    if not os.environ.get("GEMINI_API_KEY"):
        return jsonify({
            "error": "GEMINI_API_KEY is not configured on the server. Please check your .env file."
        }), 500


def sanitize_text(text):
    """Strips HTML tags from the given text and clips to maximum length."""
    if not text:
        return ""
    # Strip HTML tags
    clean = re.sub(r"<[^>]*>", "", text)
    # Return stripped and clipped text
    return clean.strip()[:MAX_JOURNAL_CHARS]


def read_journal_data():
    """Reads the journal JSON file. Initializes as empty array if missing.

    Raises ValueError if JSON is corrupt, which returns a 500 error.
    """
    if not os.path.exists(DATA_FILE):
        write_journal_data([])
        return []

    try:
        with open(DATA_FILE, "r", encoding="utf-8") as f:
            content = f.read().strip()
            if not content:
                return []
            return json.loads(content)
    except json.JSONDecodeError as e:
        raise ValueError(f"Database corruption: Failed to parse {DATA_FILE}. Detailed error: {str(e)}")
    except Exception as e:
        raise IOError(f"Database Read Error: Unable to access {DATA_FILE}. Error: {str(e)}")


def write_journal_data(data):
    """Writes the journal data array back to the JSON file."""
    try:
        with open(DATA_FILE, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    except Exception as e:
        raise IOError(f"Database Write Error: Unable to save to {DATA_FILE}. Error: {str(e)}")


def call_gemini_json(prompt, system_instruction=None):
    """Calls Gemini 1.5 Flash expecting a structured JSON response."""
    try:
        generation_config = {"response_mime_type": "application/json"}
        model = genai.GenerativeModel(
            model_name=GEMINI_MODEL_NAME,
            system_instruction=system_instruction,
            generation_config=generation_config
        )
        response = model.generate_content(prompt)
        text = response.text.strip()

        # Clean markdown code fences if generated by accident
        if text.startswith("```json"):
            text = text[7:]
        if text.endswith("```"):
            text = text[:-3]
        text = text.strip()

        try:
            return json.loads(text)
        except json.JSONDecodeError as parse_err:
            raise ValueError(f"JSON Parse Failure on Gemini response. Error: {str(parse_err)}. Content: {text}")

    except Exception as e:
        raise RuntimeError(f"Gemini API failure: {str(e)}")


def call_gemini_text(prompt, system_instruction=None):
    """Calls Gemini 1.5 Flash expecting a plain text response."""
    try:
        model = genai.GenerativeModel(
            model_name=GEMINI_MODEL_NAME,
            system_instruction=system_instruction
        )
        response = model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        raise RuntimeError(f"Gemini API failure: {str(e)}")


@app.errorhandler(ValueError)
def handle_value_error(e):
    """Global handler for data corruption and JSON parsing errors."""
    return jsonify({"error": str(e)}), 500


@app.errorhandler(IOError)
def handle_io_error(e):
    """Global handler for file read/write errors."""
    return jsonify({"error": str(e)}), 500


@app.route("/")
def index():
    """Serves the frontend SPA landing page."""
    return send_from_directory(".", "index.html")


@app.route("/journal", methods=["POST"])
def save_journal():
    """Validates and saves a new journal entry without stress scores."""
    data = request.json or {}
    text = data.get("text", "")
    mood = data.get("mood", "")
    exam = data.get("exam", "")
    exam_date = data.get("exam_date", None)

    # Validation
    sanitized_text = sanitize_text(text)
    if not sanitized_text:
        return jsonify({"error": "Journal text cannot be empty."}), 400

    if not mood:
        return jsonify({"error": "Mood parameter is required."}), 400

    if not exam:
        return jsonify({"error": "Target exam is required."}), 400

    # Read existing database
    entries = read_journal_data()

    # Construct new entry
    new_entry = {
        "id": str(uuid.uuid4()),
        "timestamp": datetime.datetime.utcnow().isoformat() + "Z",
        "mood": mood,
        "exam": exam,
        "exam_date": exam_date if exam_date else None,
        "text": sanitized_text,
        "stress_level": None,
        "emotions": []
    }

    entries.append(new_entry)
    write_journal_data(entries)

    return jsonify(new_entry), 201


@app.route("/analyze", methods=["POST"])
def analyze_journal():
    """Calls Gemini to analyze the text of an entry, updating it in the datastore."""
    data = request.json or {}
    entry_id = data.get("id")

    if not entry_id:
        return jsonify({"error": "Entry ID is required."}), 400

    entries = read_journal_data()
    matching_entry = next((e for e in entries if e["id"] == entry_id), None)

    if not matching_entry:
        return jsonify({"error": f"Journal entry with ID {entry_id} not found."}), 404

    system_prompt = (
        "You are an empathetic mental wellness coach for Indian students under exam pressure. "
        "Analyze this ACTUAL journal entry and mood ONLY. Return valid JSON:\n"
        "{\n"
        "  \"stress_level\": 1-10 integer,\n"
        "  \"detected_emotions\": [exactly 3 emotion strings],\n"
        "  \"hidden_triggers\": [2-3 India-specific triggers from the text],\n"
        "  \"coping_strategy\": \"specific actionable tip (2-3 sentences)\",\n"
        "  \"mindfulness_exercise\": \"2-minute exercise for their stress\",\n"
        "  \"motivational_message\": \"personalized, mentions their exam\",\n"
        "  \"india_context\": \"culturally relevant insight from the entry\",\n"
        "  \"safety_flag\": true or false\n"
        "}\n"
        "Return only valid JSON. Do not invent or assume anything not present in the journal entry."
    )

    user_prompt = f"Journal Entry text: '{matching_entry['text']}'\nMood Logged: '{matching_entry['mood']}'"

    try:
        analysis = call_gemini_json(user_prompt, system_instruction=system_prompt)
        
        # Validate that the returned data matches the expected structure
        required_keys = [
            "stress_level", "detected_emotions", "hidden_triggers", 
            "coping_strategy", "mindfulness_exercise", "motivational_message", 
            "india_context", "safety_flag"
        ]
        for key in required_keys:
            if key not in analysis:
                raise ValueError(f"Missing expected key '{key}' in Gemini output.")

        # Update entry in data store
        matching_entry["stress_level"] = int(analysis["stress_level"])
        matching_entry["emotions"] = list(analysis["detected_emotions"])
        
        write_journal_data(entries)
        
        return jsonify(analysis), 200

    except Exception as e:
        return jsonify({"error": f"Failed to complete AI analysis: {str(e)}"}), 502


@app.route("/burnout-predict", methods=["POST"])
def predict_burnout():
    """Predicts burnout risk trends based on 3+ journal entries."""
    entries = read_journal_data()

    if len(entries) < MIN_BURNOUT_ENTRIES:
        return jsonify({"insufficient_data": True}), 200

    # Format the real entries for the prompt
    formatted_entries = []
    for idx, entry in enumerate(entries):
        formatted_entries.append(
            f"Entry {idx + 1} ({entry['timestamp']}): Mood={entry['mood']}, Stress={entry['stress_level']}, Text='{entry['text']}'"
        )
    entries_text = "\n".join(formatted_entries)

    system_prompt = (
        "Analyze ONLY these actual journal entries (do not invent any data). "
        "Based on the real stress pattern, return JSON:\n"
        "{\n"
        "  \"burnout_risk\": \"low|medium|high|critical\",\n"
        "  \"days_until_burnout\": integer or null,\n"
        "  \"warning_signs\": [3 signs actually found in entries],\n"
        "  \"intervention\": \"3-step plan based on real patterns\"\n"
        "}\n"
        "Return only valid JSON, no markdown, no invented data."
    )

    try:
        prediction = call_gemini_json(entries_text, system_instruction=system_prompt)
        
        # Verify required keys
        required_keys = ["burnout_risk", "days_until_burnout", "warning_signs", "intervention"]
        for key in required_keys:
            if key not in prediction:
                raise ValueError(f"Missing expected key '{key}' in Gemini output.")
                
        return jsonify(prediction), 200
    except Exception as e:
        return jsonify({"error": f"Failed to calculate burnout prediction: {str(e)}"}), 502


@app.route("/stress-dna", methods=["POST"])
def generate_stress_dna():
    """Generates a personalized stress DNA fingerprint based on all history (min 1 entry)."""
    entries = read_journal_data()

    if not entries:
        return jsonify({"insufficient_data": True}), 200

    formatted_entries = []
    for idx, entry in enumerate(entries):
        formatted_entries.append(
            f"Entry {idx + 1} (Exam: {entry['exam']}): Mood={entry['mood']}, Stress={entry['stress_level']}, Text='{entry['text']}'"
        )
    entries_text = "\n".join(formatted_entries)

    system_prompt = (
        "Analyze ONLY these actual journal entries from an Indian exam student. Do not invent data. Return JSON:\n"
        "{\n"
        "  \"primary_stressor\": \"root cause found in entries\",\n"
        "  \"stress_pattern\": \"when stress peaks based on real entries\",\n"
        "  \"emotional_default\": \"emotional response found in entries\",\n"
        "  \"personalized_mantra\": \"Hindi/English mantra for this student\",\n"
        "  \"weekly_wins\": [up to 3 positives found; fewer if not found],\n"
        "  \"next_week_focus\": \"one micro-habit based on real patterns\"\n"
        "}\n"
        "Return only valid JSON, no markdown."
    )

    try:
        dna_report = call_gemini_json(entries_text, system_instruction=system_prompt)
        
        # Verify required keys
        required_keys = [
            "primary_stressor", "stress_pattern", "emotional_default", 
            "personalized_mantra", "weekly_wins", "next_week_focus"
        ]
        for key in required_keys:
            if key not in dna_report:
                raise ValueError(f"Missing expected key '{key}' in Stress DNA output.")
                
        return jsonify(dna_report), 200
    except Exception as e:
        return jsonify({"error": f"Failed to generate Stress DNA: {str(e)}"}), 502


@app.route("/panic-button", methods=["GET"])
def panic_button():
    """Generates a real-time customized 60-second breathing exercise plain-text."""
    prompt = (
        "Generate a unique 60-second breathing exercise for an Indian student under exam stress RIGHT NOW. "
        "Make it specific and actionable. Return plain text only."
    )
    try:
        exercise = call_gemini_text(prompt)
        return exercise, 200, {"Content-Type": "text/plain; charset=utf-8"}
    except Exception as e:
        return jsonify({"error": f"Gemini API failure: {str(e)}"}), 502


@app.route("/motivate-me", methods=["GET"])
def motivate_me():
    """Generates exam-specific motivation plain-text."""
    exam = request.args.get("exam", "General")
    prompt = (
        f"Generate one fresh, unique motivational message for a student preparing for {exam}. "
        f"Make it specific to their exam's challenges. Return plain text only. No generic quotes."
    )
    try:
        message = call_gemini_text(prompt)
        return message, 200, {"Content-Type": "text/plain; charset=utf-8"}
    except Exception as e:
        return jsonify({"error": f"Gemini API failure: {str(e)}"}), 502


@app.route("/dashboard", methods=["GET"])
def get_dashboard_data():
    """Calculates daily statistics, streaks, and top emotions from entries."""
    try:
        entries = read_journal_data()
    except (ValueError, IOError) as e:
        return jsonify({"error": str(e)}), 500

    if not entries:
        return jsonify({"entries": [], "empty": True}), 200

    # Calculate stress by date
    stress_by_date = {}
    # Count of stress levels per date to average later
    stress_counts = {}

    # Calculate top emotions
    top_emotions = {}

    # Unique dates set for streak calculation
    unique_dates = set()

    for entry in entries:
        # Extract YYYY-MM-DD from ISO format timestamp
        dt_str = entry["timestamp"].split("T")[0]
        unique_dates.add(dt_str)

        # Average stress levels
        stress = entry.get("stress_level")
        if stress is not None:
            stress_by_date[dt_str] = stress_by_date.get(dt_str, 0.0) + float(stress)
            stress_counts[dt_str] = stress_counts.get(dt_str, 0) + 1

        # Emotions count
        for emo in entry.get("emotions", []):
            if emo:
                top_emotions[emo] = top_emotions.get(emo, 0) + 1

    # Finish average stress calculation
    for dt in stress_by_date:
        if stress_counts[dt] > 0:
            stress_by_date[dt] = round(stress_by_date[dt] / stress_counts[dt], 1)

    # Streak Calculation
    sorted_dates = sorted([datetime.datetime.strptime(d, "%Y-%m-%d").date() for d in unique_dates], reverse=True)
    streak = 0
    if sorted_dates:
        today = datetime.datetime.utcnow().date()
        yesterday = today - datetime.timedelta(days=1)

        # Streak is active only if they journaled today or yesterday
        if sorted_dates[0] in (today, yesterday):
            streak = 1
            current_date = sorted_dates[0]
            for next_date in sorted_dates[1:]:
                if (current_date - next_date).days == 1:
                    streak += 1
                    current_date = next_date
                elif (current_date - next_date).days == 0:
                    continue  # Same day entry
                else:
                    break  # Gap in dates

    return jsonify({
        "entries_count": len(entries),
        "stress_by_date": stress_by_date,
        "top_emotions": top_emotions,
        "streak_days": streak
    }), 200


@app.route("/chat", methods=["POST"])
def chat():
    """Facilitates an empathetic chat response from Gemini."""
    data = request.json or {}
    messages = data.get("messages", [])
    exam = data.get("exam", "General")
    mood = data.get("mood", "Neutral")

    if not messages:
        return jsonify({"error": "No messages provided."}), 400

    system_instruction = (
        f"You are an empathetic, supportive mental wellness coach for Indian students preparing for competitive exams "
        f"like JEE, NEET, CUET, CAT, GATE, UPSC, or Board exams. "
        f"The student is currently preparing for {exam} and is feeling {mood}. "
        f"Keep your response concise, culturally relevant (referencing the intense pressure in India), supportive, "
        f"and limited to 2-3 sentences. Do not offer clinical advice, and act as a friendly guide. "
        f"Respond with empathy."
    )

    prompt_lines = []
    # Take at most the last 5 messages for context
    for msg in messages[-5:]:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        speaker = "Student" if role == "user" else "Coach"
        prompt_lines.append(f"{speaker}: {content}")
    
    prompt_lines.append("Coach:")
    prompt = "\n".join(prompt_lines)

    try:
        response_text = call_gemini_text(prompt, system_instruction=system_instruction)
        return jsonify({"response": response_text}), 200
    except Exception as e:
        return jsonify({"error": f"Failed to fetch AI response: {str(e)}"}), 502


if __name__ == "__main__":
    # In development, bind to PORT in .env or default to 5000
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=(ENV == "development"))
